## 1. Análisis Inicial de datos

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\ASUS\Desktop\Proyectos Big data\1. Manufactura\archive\synthetic_industrial_machine_data.csv")
df.head()

,transaction_date,asset_tag,machine_type,plant_code,part_no,part_description,part_family,criticality,uom,unit_cost_inr,...,temp_bearing_degC,temp_motor_degC,vibration_h_mms,vibration_v_mms,oil_pressure_bar,load_pct,shaft_rpm,power_consumption_kw,breakdown_flag,wo_type
0,2022-01-03,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,63.3,63.5,4.944,3.886,3.71,85.9,1794,16.09,0,NaN
1,2022-01-04,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.0,64.8,4.614,3.530,3.67,82.0,1790,15.53,0,NaN
2,2022-01-05,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.4,66.7,4.360,2.976,3.74,83.0,1827,16.20,0,NaN
3,2022-01-06,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.5,68.1,4.522,3.315,3.90,82.9,1811,16.47,0,NaN
4,2022-01-07,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,62.2,66.3,4.340,3.434,3.71,80.1,1810,15.08,0,NaN

## Análisis exploratorio de datos y Limpieza

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 219000 entries, 0 to 218999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_date      219000 non-null  str
 1   asset_tag             219000 non-null  str
 2   machine_type          219000 non-null  str
 3   plant_code            219000 non-null  str
 4   part_no               219000 non-null  str
 5   part_description      219000 non-null  str
 6   part_family           219000 non-null  str
 7   criticality           219000 non-null  str
 8   uom                   219000 non-null  str
 9   unit_cost_inr         219000 non-null  int64
 10  qty_issued            219000 non-null  int64
 11  issue_value_inr       219000 non-null  int64
 12  temp_bearing_degC     219000 non-null  float64
 13  temp_motor_degC       219000 non-null  float64
 14  vibration_h_mms       219000 non-null  float64
 15  vibration_v_mms       219000 non-null  float64
 16  oil_pressure_bar      219000 non-null  float64
 17  load_pct              219000 non-null  float64
 18  shaft_rpm             219000 non-null  int64
 19  power_consumption_kw  219000 non-null  float64
 20  breakdown_flag        219000 non-null  int64
 21  wo_type               42793 non-null   str
dtypes: float64(7), int64(5), str(10)
memory usage: 54.7 MB

In [4]:
df.head()

,transaction_date,asset_tag,machine_type,plant_code,part_no,part_description,part_family,criticality,uom,unit_cost_inr,...,temp_bearing_degC,temp_motor_degC,vibration_h_mms,vibration_v_mms,oil_pressure_bar,load_pct,shaft_rpm,power_consumption_kw,breakdown_flag,wo_type
0,2022-01-03,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,63.3,63.5,4.944,3.886,3.71,85.9,1794,16.09,0,NaN
1,2022-01-04,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.0,64.8,4.614,3.530,3.67,82.0,1790,15.53,0,NaN
2,2022-01-05,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.4,66.7,4.360,2.976,3.74,83.0,1827,16.20,0,NaN
3,2022-01-06,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.5,68.1,4.522,3.315,3.90,82.9,1811,16.47,0,NaN
4,2022-01-07,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,62.2,66.3,4.340,3.434,3.71,80.1,1810,15.08,0,NaN

Rellenar variables numéricas con la MEDIANA

In [5]:
# Rellenar nulos en variables numéricas (sensores y métricas) con la mediana
columnas_numericas = df.select_dtypes(include=[np.number]).columns
for col in columnas_numericas:
    df[col] = df[col].fillna(df[col].median())

Rellenar variables Categóricas con 'No_Registrado'

In [6]:
# Rellenar nulos en variables categóricas con un texto predeterminado
columnas_categoricas = ['asset_tag', 'machine_type', 'plant_code','part_description', 'part_family', 'criticality', 'uom']
for col in columnas_categoricas:
    if col in df.columns:
        df[col] = df[col].fillna('No_Registrado')

In [7]:
# Conteo de valores NULOS

print("--- CONTEO DE VALORES NULOS ---")
nulos_por_columna = df.isnull().sum()
columnas_con_nulos = nulos_por_columna[nulos_por_columna > 0]

if not columnas_con_nulos.empty:
    print(columnas_con_nulos)
else:
    print("¡Excelente! No hay valores nulos en ninguna columna.")

print(f"Total general de celdas nulas: {df.isnull().sum().sum()}")
print("-" * 40)

--- CONTEO DE VALORES NULOS ---
wo_type    176207
dtype: int64
Total general de celdas nulas: 176207
----------------------------------------

In [8]:
print("--- CONTEO DE FILAS DUPLICADAS ---")
filas_duplicadas = df.duplicated().sum()

print(f"Total de filas exactamente iguales (repetidas): {filas_duplicadas}")

--- CONTEO DE FILAS DUPLICADAS ---
Total de filas exactamente iguales (repetidas): 0

In [9]:
resumen_columnas = pd.DataFrame({
    'Columna': df.columns,
    'Tipo_Dato': df.dtypes.values,
    'Valores_Nulos': df.isnull().sum().values,
    'Valores_No_Nulos': df.notnull().sum().values,
    'Valores_Unicos': df.nunique().values
})

# 3. Mostrar la tabla organizada en la consola
print("=== RESUMEN GENERAL POR COLUMNA ===")
print(resumen_columnas.to_string(index=False))

# 4. Mostrar filas completamente duplicadas (si las hay)
filas_duplicadas = df.duplicated().sum()
print(f"\nTotal de filas completamente repetidas en el archivo: {filas_duplicadas}")

=== RESUMEN GENERAL POR COLUMNA ===
             Columna Tipo_Dato  Valores_Nulos  Valores_No_Nulos  Valores_Unicos
    transaction_date       str              0            219000            1095
           asset_tag       str              0            219000              10
        machine_type       str              0            219000               5
          plant_code       str              0            219000               3
             part_no       str              0            219000              20
    part_description       str              0            219000              20
         part_family       str              0            219000               9
         criticality       str              0            219000               3
                 uom       str              0            219000               5
       unit_cost_inr     int64              0            219000              20
          qty_issued     int64              0            219000               8
     issue_value_inr     int64              0            219000              32
   temp_bearing_degC   float64              0            219000             275
     temp_motor_degC   float64              0            219000             326
     vibration_h_mms   float64              0            219000            3645
     vibration_v_mms   float64              0            219000            3103
    oil_pressure_bar   float64              0            219000             390
            load_pct   float64              0            219000             547
           shaft_rpm     int64              0            219000             572
power_consumption_kw   float64              0            219000            3821
      breakdown_flag     int64              0            219000               2
             wo_type       str         176207             42793               2

Total de filas completamente repetidas en el archivo: 0